// Objetivos del plan por nivel y mesociclo: del mesociclo (13 semanas), de cada mes (Mes 1 = S0–S4,
// Mes 2 = S5–S8, Mes 3 = S9–S12) y de cada semana. Se muestran en el Mapa del ciclo (components/MapaCiclo.jsx)
// para que el escalador entienda por qué hace lo que hace.
// Redactados a partir de las sesiones del plan base (plan_contenido). BORRADOR: revisar con el equipo.
//
// tipo de semana: test · carga · pico (máxima carga del bloque) · descarga · rendimiento

const S = (fase, tipo, objetivo) => ({ fase, tipo, objetivo });

export const OBJETIVOS = {
  iniciacion: {
    T1: {
      titulo: 'Fundamentos: caer, pisar y leer',
      objetivo: 'Perder el miedo a caer, pisar con precisión y leer tus primeras vías. Cero trabajo de dedos: aquí se construye la técnica que sostiene todo lo demás.',
      meses: [
        { titulo: 'Caída y pies', objetivo: 'Medir tu punto de partida, caer con control y aprender a pisar: agarres básicos, flag y cambio de pie.' },
        { titulo: 'Vías reales', objetivo: 'Asimilar con una semana suave y llevar las técnicas a vías reales: a vista, ritmo y continuidad.' },
        { titulo: 'Consolidar', objetivo: 'Sostener la técnica con cansancio, intentar un grado superior y medir tu progreso.' },
      ],
      semanas: {
        S0: S('Evaluación', 'test', 'Medir tu técnica de partida y planear el ciclo.'),
        S1: S('Base', 'carga', 'Caer con control y pisar en silencio.'),
        S2: S('Agarres', 'carga', 'Tres tipos de agarre y leer los primeros pasos.'),
        S3: S('Flag', 'carga', 'Flag lateral y cambio de pie para mover mejor el cuerpo.'),
        S4: S('Integrar', 'pico', 'Unir pies, flags y lectura en la misma sesión.'),
        S5: S('Descarga', 'descarga', 'Escalar suave para asimilar lo aprendido.'),
        S6: S('A vista', 'carga', 'Leer y escalar a vista en vías reales.'),
        S7: S('Ritmo', 'carga', 'Escalar con ritmo y probar más dificultad.'),
        S8: S('Continuidad', 'pico', 'Mantener la técnica aunque llegue el cansancio.'),
        S9: S('Continuidad', 'pico', 'Máxima continuidad y técnica filmada para corregir.'),
        S10: S('Descarga', 'descarga', 'Bajar la carga para llegar fresco al cierre.'),
        S11: S('Grado superior', 'rendimiento', 'Intentar el grado superior y ensayar el test.'),
        S12: S('Test de salida', 'test', 'Medir cuánto mejoraste frente a S0.'),
      },
    },
    T2: {
      titulo: 'Perfiles: placa, desplome y diedro',
      objetivo: 'Adaptar tu técnica a cada inclinación del muro —cadera pegada en placa, cadera baja en desplome, oposición en diedro— y sumar talonaje y lolotte.',
      meses: [
        { titulo: 'Un perfil a la vez', objetivo: 'Aprender la técnica propia de placa, desplome y diedro, y luego combinarlos.' },
        { titulo: 'Combinar perfiles', objetivo: 'Usar ritmo variable y lectura de 4 pasos para elegir la técnica correcta en cada sección.' },
        { titulo: 'Consolidar', objetivo: 'Sostener las técnicas con cansancio, rendir en tu mejor perfil y medir tu progreso.' },
      ],
      semanas: {
        S0: S('Evaluación', 'test', 'Medir tu técnica al iniciar el T2.'),
        S1: S('Placa', 'carga', 'Placa: cadera pegada y pies silenciosos.'),
        S2: S('Desplome', 'carga', 'Desplome: cadera baja, flags y primer talonaje.'),
        S3: S('Diedro', 'carga', 'Diedro: oposición y lolotte.'),
        S4: S('Combinar', 'pico', 'Cambiar de técnica según el perfil en la misma sesión.'),
        S5: S('Descarga', 'descarga', 'Escalar suave y revisar con tu entrenador.'),
        S6: S('Ritmo', 'carga', 'Ritmo variable y leer qué técnica pide cada sección.'),
        S7: S('A vista', 'carga', 'A vista en perfiles variados y caída en desplome.'),
        S8: S('Fatiga', 'pico', 'Usar las técnicas avanzadas aunque haya cansancio.'),
        S9: S('Continuidad', 'pico', '45–50 movimientos seguidos y técnica filmada.'),
        S10: S('Descarga', 'descarga', 'Bajar la carga antes del cierre.'),
        S11: S('Al máximo', 'rendimiento', 'Tus vías al máximo y ensayo del test.'),
        S12: S('Test de salida', 'test', 'Medir cuánto mejoraste frente a S0.'),
      },
    },
    T3: {
      titulo: 'Economía y caída en primero',
      objetivo: 'Escalar más con menos esfuerzo —ritmo fluido, reposos activos, brazos extendidos— y empezar a caer en primero con seguridad.',
      meses: [
        { titulo: 'Ritmo y economía', objetivo: 'Analizar tu ritmo, aplicar los principios de economía y dar tus primeras caídas en primero.' },
        { titulo: 'Integrar', objetivo: 'Leer más rápido y unir ritmo, reposos y economía en vías más largas.' },
        { titulo: 'Continuidad larga', objetivo: 'Llegar a 90–100 movimientos seguidos y medir tu progreso.' },
      ],
      semanas: {
        S0: S('Evaluación', 'test', 'Evaluar el T2 y medir tu continuidad inicial.'),
        S1: S('Ritmo', 'carga', 'Analizar tu ritmo y encontrar reposos activos.'),
        S2: S('Economía', 'carga', 'Brazos extendidos, ritmo fluido y caída en primero.'),
        S3: S('Reposos', 'carga', 'Reposos deliberados y lectura en 90 segundos.'),
        S4: S('Integrar', 'pico', 'Ritmo, reposos y economía juntos en 6 vías.'),
        S5: S('Descarga', 'descarga', 'Escalar suave y revisión con tu entrenador.'),
        S6: S('Continuidad 70', 'carga', '70 movimientos seguidos y lectura en 60 segundos.'),
        S7: S('Integración', 'carga', 'Unir todo en vías difíciles.'),
        S8: S('Continuidad 80', 'pico', '80 movimientos y caída en primero en un intento real.'),
        S9: S('Continuidad 100', 'pico', '90–100 movimientos y técnica filmada.'),
        S10: S('Descarga', 'descarga', 'Bajar la carga y preparar la mente para el test.'),
        S11: S('Al máximo', 'rendimiento', 'Vías al máximo con todo tu repertorio.'),
        S12: S('Test de salida', 'test', 'Medir cuánto mejoraste frente a S0.'),
      },
    },
    T4: {
      titulo: 'Proyecto y autonomía',
      objetivo: 'Pulir tu técnica, trabajar un proyecto por secciones y aprender a planear tus propias sesiones. Cierras el año con el test anual.',
      meses: [
        { titulo: 'Corregir y dividir', objetivo: 'Corregir tu gesto y trabajar el proyecto por secciones hasta el primer intento completo.' },
        { titulo: 'Autonomía', objetivo: 'Planear tus propias sesiones y atacar el proyecto con táctica.' },
        { titulo: 'Cerrar el año', objetivo: 'Buscar el encadene, ensayar el test y decidir tu paso de nivel.' },
      ],
      semanas: {
        S0: S('Evaluación', 'test', 'Test anual de entrada y plan del T4.'),
        S1: S('Corrección', 'carga', 'Corregir técnica y trabajar las secciones A y B.'),
        S2: S('Enlaces', 'carga', 'Enlazar secciones y planear tu primera sesión.'),
        S3: S('Primer intento', 'carga', 'Primer intento completo al proyecto.'),
        S4: S('Intentos', 'pico', 'Intentos completos con descanso planificado.'),
        S5: S('Descarga', 'descarga', 'Escalar suave y visualizar el proyecto.'),
        S6: S('Autónomo', 'carga', 'Ejecutar la sesión que tú mismo planeaste.'),
        S7: S('Proyecto', 'carga', 'Proyecto al inicio de la sesión, con la mente fresca.'),
        S8: S('Intentos', 'pico', 'Dos días de intentos con máxima concentración.'),
        S9: S('Encadene', 'rendimiento', 'Encadenar o preparar el test.'),
        S10: S('Descarga', 'descarga', 'Bajar la carga y preparar la mente.'),
        S11: S('Consolidar', 'rendimiento', 'Proyecto final o encadenes de consolidación.'),
        S12: S('Test anual', 'test', 'Test anual y decisión de promoción.'),
      },
    },
  },

  intermedio: {
    T1: {
      titulo: 'Base y punto débil',
      objetivo: 'Encontrar tu punto débil y construir la base: continuidad, primeras suspensiones y física general. Cierras con un proyecto del trimestre.',
      meses: [
        { titulo: 'Base', objetivo: 'Definir tu punto débil y construir continuidad, tracciones y suspensiones introductorias.' },
        { titulo: 'Circuitos', objetivo: 'Pasar de la continuidad a los circuitos: más intensidad sostenida y técnica con cansancio.' },
        { titulo: 'Proyecto', objetivo: 'Circuitos al 90%, intentos al proyecto del trimestre y test de salida.' },
      ],
      semanas: {
        S0: S('Evaluación', 'test', 'Test completo y definir tu punto débil.'),
        S1: S('Base', 'carga', 'Continuidad y técnica de tu punto débil.'),
        S2: S('Suspensiones', 'carga', 'Primeras suspensiones y técnica en 3 perfiles.'),
        S3: S('Construcción', 'carga', 'Suspensiones, talonajes y memorizar vías.'),
        S4: S('Pico de carga', 'pico', 'Continuidad máxima y suspensiones plenas.'),
        S5: S('Descarga', 'descarga', 'Bajar la carga y revisar tu PSE con el entrenador.'),
        S6: S('Circuitos', 'carga', 'Circuitos homogéneos y técnica con cansancio.'),
        S7: S('Densidad', 'carga', 'Más densidad y 2 betas por problema.'),
        S8: S('Pico de carga', 'pico', 'Circuitos de alta densidad y a vista al máximo.'),
        S9: S('Afinar', 'carga', 'Circuitos al 90% y técnica filmada.'),
        S10: S('Descarga', 'descarga', 'Bajar la carga antes del proyecto.'),
        S11: S('Proyecto', 'rendimiento', 'Intentos al proyecto con táctica de descansos.'),
        S12: S('Test de salida', 'test', 'Medir cuánto mejoraste frente a S0.'),
      },
    },
    T2: {
      titulo: 'Resistencia y lectura',
      objetivo: 'Aguantar más tiempo cerca de tu límite con circuitos personales y suspensiones, y leer mejor: a vista, memorización y lectura de 4 pasos.',
      meses: [
        { titulo: 'Circuitos y lectura', objetivo: 'Construir tus circuitos personales y entrenar a vista con lectura de 4 pasos y memorización.' },
        { titulo: 'Densidad máxima', objetivo: 'Circuitos cerca del máximo y simulación a vista tipo competencia.' },
        { titulo: 'Circuito objetivo', objetivo: 'Atacar tu circuito o vía objetivo con táctica y medir tu progreso.' },
      ],
      semanas: {
        S0: S('Evaluación', 'test', 'Tests de entrada y diseño de tus circuitos.'),
        S1: S('Base', 'carga', 'Circuitos base y lectura de 4 pasos.'),
        S2: S('Memoria', 'carga', 'Memorizar 30 movimientos y ejecutarlos.'),
        S3: S('Densidad', 'carga', 'Más densidad en suspensiones y tracciones.'),
        S4: S('Pico de carga', 'pico', 'Circuitos pico y 5 vías a vista al máximo.'),
        S5: S('Descarga', 'descarga', 'Recuperar para asimilar la carga.'),
        S6: S('Cerca del máximo', 'carga', 'Circuitos cerca del máximo y betas por sección.'),
        S7: S('Competencia', 'carga', 'Reposos activos y a vista formato competencia.'),
        S8: S('Pico de carga', 'pico', 'Circuitos al máximo sostenible.'),
        S9: S('Táctica', 'rendimiento', 'Intentos al circuito objetivo con táctica.'),
        S10: S('Descarga', 'descarga', 'Bajar la carga antes de los intentos.'),
        S11: S('Objetivo', 'rendimiento', 'Intentos al circuito o vía objetivo.'),
        S12: S('Test de salida', 'test', 'Medir cuánto mejoraste frente a S0.'),
      },
    },
    T3: {
      titulo: 'Bloque y potencia',
      objetivo: 'Llevar tu fuerza al bloque —isométricos, tracciones explosivas, lanzamientos— y aprender a gestionar intentos en tus bloques-proyecto.',
      meses: [
        { titulo: 'Fuerza en bloque', objetivo: 'Bloques al 85–95%, isométricos y tracciones explosivas; resolver una sección de 2–3 formas.' },
        { titulo: 'Dinámicos', objetivo: 'Lanzamientos, contrastes y gestión de intentos en tus bloques-proyecto.' },
        { titulo: 'Encadenar', objetivo: 'Enlaces finales, día de encadenes y test de salida.' },
      ],
      semanas: {
        S0: S('Evaluación', 'test', 'Tests y elegir tus bloques-proyecto.'),
        S1: S('Base', 'carga', 'Bloque al 85% e isométrico introductorio.'),
        S2: S('Fuerza', 'carga', 'Bloque al 90–95% y tracciones explosivas.'),
        S3: S('Lanzamientos', 'carga', 'Lanzamientos y técnica fina filmada.'),
        S4: S('Pico de carga', 'pico', 'Bloque al máximo y a vista tipo competencia.'),
        S5: S('Descarga', 'descarga', 'Bajar la carga y escalar con placer.'),
        S6: S('Dinámicos', 'carga', 'Dinámicos, contrastes y betas por 3 métodos.'),
        S7: S('Intentos', 'carga', 'Gestionar intentos en tus bloques-proyecto.'),
        S8: S('Pico de carga', 'pico', 'Sesión completa de intentos y competencia 6 × 4′.'),
        S9: S('Enlaces', 'rendimiento', 'Enlaces finales y visualización.'),
        S10: S('Descarga', 'descarga', 'Llegar fresco a los encadenes.'),
        S11: S('Encadenes', 'rendimiento', 'Día de encadenes con descansos completos.'),
        S12: S('Test de salida', 'test', 'Medir cuánto mejoraste frente a S0.'),
      },
    },
    T4: {
      titulo: 'Proyecto anual',
      objetivo: 'Elegir tu proyecto del año, corregir tu gesto y encadenarlo con táctica. Cierras con el test anual y la decisión de promoción.',
      meses: [
        { titulo: 'Corregir y preparar', objetivo: 'Corregir tu gesto y trabajar el proyecto por secciones hasta los primeros intentos completos.' },
        { titulo: 'Intentos de calidad', objetivo: 'Intentar el proyecto en tus mejores condiciones y simular una mini-competencia.' },
        { titulo: 'Encadenar y cerrar', objetivo: 'Confirmar el encadene, mini-competencia de cohorte y test anual.' },
      ],
      semanas: {
        S0: S('Evaluación', 'test', 'Tests y elegir tu proyecto anual.'),
        S1: S('Corrección', 'carga', 'Corregir el gesto y trabajar secciones.'),
        S2: S('Aplicar', 'carga', 'Aplicar la corrección con cansancio y enlazar mitades.'),
        S3: S('Enlaces', 'carga', 'Enlaces largos y primeros intentos completos.'),
        S4: S('Intentos', 'pico', 'Intentos completos con táctica (15–20 min).'),
        S5: S('Descarga', 'descarga', 'Recuperar y visualizar el proyecto.'),
        S6: S('Calidad', 'rendimiento', 'Intentos en tus mejores condiciones.'),
        S7: S('Simulacro', 'rendimiento', 'Simulacro de mini-competencia.'),
        S8: S('Intentos', 'pico', 'Dos días de intentos de máxima calidad.'),
        S9: S('Encadene', 'rendimiento', 'Confirmar el encadene.'),
        S10: S('Descarga', 'descarga', 'Preparar la mente para el cierre.'),
        S11: S('Competencia', 'rendimiento', 'Mini-competencia o día final del proyecto.'),
        S12: S('Test anual', 'test', 'Test anual y decisión de promoción.'),
      },
    },
  },

  avanzado: {
    T1: {
      titulo: 'Acumulación: fuerza máxima',
      objetivo: 'Construir la fuerza máxima del año: un bloque de acumulación, un ciclo excéntrico y la reconversión al rendimiento. Es la base de tus dos picos.',
      meses: [
        { titulo: 'Acumulación', objetivo: 'Subir la carga semana a semana en fuerza máxima, continuidad y campus, sin perder calidad técnica.' },
        { titulo: 'Excéntrico', objetivo: 'Descargar y entrar al ciclo excéntrico: es normal sentirse pesado y lento.' },
        { titulo: 'Reconversión', objetivo: 'Convertir la fuerza en rendimiento: de entrenar a rendir, y test de salida.' },
      ],
      semanas: {
        S0: S('Empalme', 'test', 'Mídete sin buscar marcas.'),
        S1: S('Reintro', 'carga', 'Volver con cargas deliberadamente bajas.'),
        S2: S('Construcción', 'carga', 'Aumentar la carga progresivamente.'),
        S3: S('Carga alta', 'carga', 'Primer pico de carga con calidad técnica.'),
        S4: S('Pico acum.', 'pico', 'Máxima carga del bloque, con fisioterapia.'),
        S5: S('Descarga', 'descarga', 'Obligatoria: no aumentes el volumen.'),
        S6: S('Excéntrico ①', 'carga', 'Iniciar el ciclo excéntrico.'),
        S7: S('Excéntrico ②', 'carga', 'Subir el excéntrico; sentirse pesado es normal.'),
        S8: S('Excéntrico ③', 'pico', 'Último excéntrico del año.'),
        S9: S('Reconversión', 'carga', 'Cambiar hacia el rendimiento.'),
        S10: S('Desc. corta', 'descarga', 'Descargar antes de la realización.'),
        S11: S('Realización', 'rendimiento', 'De entrenar a rendir.'),
        S12: S('Test de salida', 'test', 'Test de salida y cierre del T1.'),
      },
    },
    T2: {
      titulo: 'Pico 1',
      objetivo: 'Llevar al máximo tu primer pico del año: circuitos que replican tu objetivo, simulaciones y táctica, hasta la competencia o los intentos definitivos.',
      meses: [
        { titulo: 'Específico', objetivo: 'Circuitos y suspensiones que replican el perfil de tu objetivo, hasta la simulación completa.' },
        { titulo: 'Afinar', objetivo: 'Intentos reales al proyecto, táctica, técnica mental y ensayo general.' },
        { titulo: 'Pico', objetivo: 'Bajar el volumen, llegar fresco y rendir en el evento.' },
      ],
      semanas: {
        S0: S('Empalme', 'test', 'Tests y calendario fino del pico.'),
        S1: S('Base', 'carga', 'Circuitos base y suspensiones máximas.'),
        S2: S('Al límite', 'carga', 'Bloque al límite y lanzamientos.'),
        S3: S('Específico', 'carga', 'Circuitos que replican tu objetivo.'),
        S4: S('Simulación', 'pico', 'Simulación completa del objetivo.'),
        S5: S('Descarga', 'descarga', 'Recuperar y visualizar el objetivo.'),
        S6: S('Proyecto', 'rendimiento', 'Intentos reales al proyecto.'),
        S7: S('Táctica', 'rendimiento', 'Táctica de intentos y rutinas mentales.'),
        S8: S('Ensayo', 'pico', 'Ensayo general con el protocolo del evento.'),
        S9: S('Afinar', 'carga', 'Menos volumen: activación y logística.'),
        S10: S('Descarga', 'descarga', 'Sensaciones y descanso antes del evento.'),
        S11: S('Evento', 'rendimiento', 'Competencia o intentos definitivos.'),
        S12: S('Cierre', 'test', 'Cerrar el pico y test de salida reducido.'),
      },
    },
    T3: {
      titulo: 'Potencia hacia el pico 2',
      objetivo: 'Recuperar del primer pico y construir potencia —dinámicos, campus, intermitente— para llegar con nuevas herramientas al segundo pico.',
      meses: [
        { titulo: 'Recuperar y potenciar', objetivo: 'Recuperar del pico y luego trabajar dinámicos, contrastes y campus.' },
        { titulo: 'Intermitente', objetivo: 'Intermitente duro, suspensiones y bloque táctico con reloj.' },
        { titulo: 'Demanda real', objetivo: 'Simular la demanda del pico 2, test de potencia y cierre.' },
      ],
      semanas: {
        S0: S('Empalme', 'test', 'Tests y análisis del pico 1.'),
        S1: S('Recuperar', 'descarga', 'Escalada suave y análisis de video del pico.'),
        S2: S('Explosivo', 'carga', 'Tracciones explosivas e intermitente intro.'),
        S3: S('Contrastes', 'carga', 'Contrastes, dinámicos y campus.'),
        S4: S('Campus', 'pico', 'Campus completo y antagonistas reforzados.'),
        S5: S('Descarga', 'descarga', 'Mantenimiento mínimo y visualización.'),
        S6: S('Intermitente', 'carga', 'Intermitente duro y bloque táctico con reloj.'),
        S7: S('Específico', 'carga', 'Circuito del perfil objetivo y técnica mental.'),
        S8: S('Pico de carga', 'pico', 'Tres días seguidos de alta carga.'),
        S9: S('Simulación', 'rendimiento', 'Simular la demanda real del pico 2.'),
        S10: S('Descarga', 'descarga', 'Descarga antes del test.'),
        S11: S('Potencia', 'rendimiento', 'Test de potencia e intentos de control.'),
        S12: S('Test de salida', 'test', 'Mejores intentos y test de salida.'),
      },
    },
    T4: {
      titulo: 'Pico 2 y cierre',
      objetivo: 'Rendir en el segundo pico del año y cerrar la temporada con el test anual y el diseño de tu próximo año.',
      meses: [
        { titulo: 'Específico final', objetivo: 'Simulaciones del evento y la última carga alta del año.' },
        { titulo: 'Afinar', objetivo: 'Bajar el volumen manteniendo la intensidad y ensayar el día del evento.' },
        { titulo: 'Evento y cierre', objetivo: 'Rendir en el evento, descargar y hacer el test anual.' },
      ],
      semanas: {
        S0: S('Empalme', 'test', 'Tests y calendario exacto del pico 2.'),
        S1: S('Específico', 'carga', 'Tu perfil objetivo a máxima calidad.'),
        S2: S('Simulación', 'carga', 'Simulación parcial y manejo de la ansiedad.'),
        S3: S('Reglamento', 'carga', 'Simulación completa con reloj y reglamento.'),
        S4: S('Última carga', 'pico', 'Última carga alta: doble simulación.'),
        S5: S('Descarga', 'descarga', 'Volumen −50%: sensaciones y fluidez.'),
        S6: S('Intensidad', 'carga', 'Intensidad máxima puntual.'),
        S7: S('Ensayo', 'rendimiento', 'Ensayo general del día del evento.'),
        S8: S('Sensaciones', 'descarga', 'Sensaciones, fisioterapia final y logística.'),
        S9: S('Evento', 'rendimiento', 'Competencia o días definitivos.'),
        S10: S('Evento', 'rendimiento', 'Extensión de la ventana o segunda competencia.'),
        S11: S('Descarga', 'descarga', 'Encadenes de celebración y descarga real.'),
        S12: S('Test anual', 'test', 'Test anual y diseño del año siguiente.'),
      },
    },
  },
};

export const objetivosDe = (nivel, trimestre) => OBJETIVOS[nivel]?.[trimestre] || null;
